// The server half of H-4, against the SHARED vectors.
//
// test/vectors/ratchet-vectors.json is consumed by this file and by
// packages/scruple-host-sdk/tests/test_ratchet.py. That is the entire
// point: two implementations that each pass their own tests and disagree
// on the wire is the failure this file exists to prevent — and per
// CANON_SKELETON it is the failure the six SDK forks actually had.
//
// The vectors were generated by the PYTHON module. So these are the
// cross-language proof: if this file passes, Node and CPython agree byte
// for byte on every IK, chain key, MAC key and MAC in the file. The
// `crypto.hkdfSync` tests below add Node's OpenSSL as an independent
// third implementation of the same construction.
//
// Deliberately DB-free. It imports lib/ratchet/ratchet and nothing that
// reaches lib/db/sqlite, so it cannot participate in the shared-database
// race between test/v2 files. Everything DB-touching is in
// test/v2/components-provision.test.ts, which uses its own private file.

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

import {
  HASH_LEN,
  INFO_IK,
  INFO_MAC,
  INFO_RATCHET,
  Ratchet,
  RatchetError,
  canonicalPreimage,
  codePointCompare,
  deriveIk,
  hkdfExpand,
  hkdfExtract,
  hkdfSha256,
  macEquals,
  macFor,
  ratchetForward,
  zeroize,
} from '../../lib/ratchet/ratchet';

const VECTORS_PATH = path.join(process.cwd(), 'test', 'vectors', 'ratchet-vectors.json');

interface Event {
  n: number;
  chain_key_hex: string;
  mac_key_hex: string;
  preimage_fields: Record<string, string | number | boolean | null>;
  canonical_preimage_utf8: string;
  mac_hex: string;
}
interface Vectors {
  construction: Record<string, string>;
  bdk_hex: string;
  cases: Array<{ component_id: string; ik_hex: string; events: Event[] }>;
  raw_preimage_cases: {
    component_id: string;
    events: Array<{
      n: number;
      preimage_hex: string;
      chain_key_hex: string;
      mac_key_hex: string;
      mac_hex: string;
    }>;
  };
  canonical_preimage_cases: Array<{
    fields: Record<string, string | number | boolean | null>;
    canonical_utf8: string;
    canonical_hex: string;
    sha256_hex: string;
  }>;
}

assert.ok(
  fs.existsSync(VECTORS_PATH),
  `shared vectors missing at ${VECTORS_PATH}. Both suites read this one file; ` +
    'if it is gone, the cross-language guarantee is gone with it.',
);
const V: Vectors = JSON.parse(fs.readFileSync(VECTORS_PATH, 'utf8'));
const BDK = Buffer.from(V.bdk_hex, 'hex');

const hex = (b: Buffer) => b.toString('hex');

// ---------------------------------------------------------------------------
// RFC 5869, so a bug in our HKDF is caught against the RFC's own numbers
// and not only against the other implementation we wrote.
// ---------------------------------------------------------------------------

describe('HKDF is RFC 5869', () => {
  test('A.1 — SHA-256 basic', () => {
    const prk = hkdfExtract(
      Buffer.from('000102030405060708090a0b0c', 'hex'),
      Buffer.from('0b'.repeat(22), 'hex'),
    );
    assert.equal(hex(prk), '077709362c2e32df0ddc3f0dc47bba6390b6c73bb50f9c3122ec844ad7c2b3e5');
    assert.equal(
      hex(hkdfExpand(prk, Buffer.from('f0f1f2f3f4f5f6f7f8f9', 'hex'), 42)),
      '3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865',
    );
  });

  test('A.3 — zero-length salt takes the HashLen-zeros path', () => {
    const prk = hkdfExtract(Buffer.alloc(0), Buffer.from('0b'.repeat(22), 'hex'));
    assert.equal(hex(prk), '19ef24a32c717b167f33a91d6f648bdf96596776afdb6377ac434c1c293ccb04');
    assert.equal(
      hex(hkdfExpand(prk, Buffer.alloc(0), 42)),
      '8da4e775a563c18f715f802a063c5a31b8a11f5c5ee1879ec3454e5f3c738d2d9d201395faa4b61a96c8',
    );
  });
});

describe("our hand-written HKDF agrees with Node's built-in", () => {
  // crypto.hkdfSync is extract+expand. Where the spec calls for full HKDF
  // — IK derivation only — the two must agree. This is what makes Node's
  // OpenSSL an independent third check on the construction.
  test('full HKDF matches crypto.hkdfSync across random inputs', () => {
    for (let i = 0; i < 64; i++) {
      const ikm = crypto.randomBytes(1 + (i % 48));
      const salt = i % 4 === 0 ? Buffer.alloc(0) : crypto.randomBytes(1 + (i % 20));
      const info = crypto.randomBytes(i % 17);
      const len = 1 + (i % 80);
      assert.equal(
        hex(hkdfSha256(ikm, salt, info, len)),
        Buffer.from(crypto.hkdfSync('sha256', ikm, salt, info, len)).toString('hex'),
        `mismatch at i=${i}`,
      );
    }
  });

  test('the IK in the vectors is what crypto.hkdfSync computes', () => {
    for (const c of V.cases) {
      const viaNode = Buffer.from(
        crypto.hkdfSync('sha256', BDK, Buffer.from(c.component_id, 'utf8'), INFO_IK, HASH_LEN),
      );
      assert.equal(hex(viaNode), c.ik_hex, c.component_id);
    }
  });
});

describe('the spec asymmetry — full HKDF for IK, Expand-only for the chain', () => {
  test('the vectors say so in words as well as numbers', () => {
    assert.match(V.construction.ik, /FULL HKDF/);
    assert.match(V.construction.mac_key, /EXPAND ONLY/);
    assert.match(V.construction.next_chain_key, /EXPAND ONLY/);
  });

  test('Expand-only is not the same as full HKDF', () => {
    // If someone later "fixes" the chain steps to use full HKDF, this
    // fails. That change is silent everywhere else and would invalidate
    // every component in the field.
    const k = Buffer.from(Array.from({ length: 32 }, (_, i) => i));
    assert.notEqual(hex(hkdfExpand(k, INFO_MAC, 32)), hex(hkdfSha256(k, Buffer.alloc(0), INFO_MAC, 32)));
  });

  test('Expand at L=32 is exactly one HMAC block: HMAC(K, info || 0x01)', () => {
    const k = Buffer.from(Array.from({ length: 32 }, (_, i) => i));
    const expected = crypto
      .createHmac('sha256', k)
      .update(Buffer.concat([INFO_RATCHET, Buffer.from([1])]))
      .digest();
    assert.equal(hex(hkdfExpand(k, INFO_RATCHET, 32)), hex(expected));
  });
});

// ---------------------------------------------------------------------------
// Cross-language parity — the point of this WO
// ---------------------------------------------------------------------------

describe('cross-language vector parity (vectors generated by ratchet.py)', () => {
  test('every IK matches', () => {
    for (const c of V.cases) {
      assert.equal(hex(deriveIk(BDK, c.component_id)), c.ik_hex, c.component_id);
    }
  });

  test('every chain key, MAC key, canonical preimage and MAC matches', () => {
    for (const c of V.cases) {
      const r = new Ratchet(deriveIk(BDK, c.component_id), 0);
      const byN = new Map(c.events.map((e) => [e.n, e]));
      const top = Math.max(...byN.keys());
      for (let n = 0; n <= top; n++) {
        const kN = r.chainKey();
        const e = byN.get(n);
        const pre = e ? canonicalPreimage(e.preimage_fields) : Buffer.from('filler', 'utf8');
        const mN = hkdfExpand(kN, INFO_MAC, HASH_LEN);
        const { counter, mac } = r.mac(pre);
        assert.equal(counter, n);
        if (e) {
          assert.equal(hex(kN), e.chain_key_hex, `K_${n} for ${c.component_id}`);
          assert.equal(hex(mN), e.mac_key_hex, `M_${n} for ${c.component_id}`);
          assert.equal(pre.toString('utf8'), e.canonical_preimage_utf8, `preimage at n=${n}`);
          assert.equal(mac, e.mac_hex, `mac at n=${n} for ${c.component_id}`);
        }
      }
    }
  });

  test('the vectors reach a large counter — a ratchet tested only at 0 and 1 is not tested', () => {
    const ns = V.cases.flatMap((c) => c.events.map((e) => e.n));
    assert.ok(ns.includes(0) && ns.includes(1));
    assert.ok(Math.max(...ns) >= 500, 'vectors must exercise ratcheting forward');
  });

  test('raw-byte preimages match — a canonicalisation bug fails separately from a MAC bug', () => {
    const b = V.raw_preimage_cases;
    const r = new Ratchet(deriveIk(BDK, b.component_id), 0);
    for (const e of b.events) {
      assert.equal(r.counter, e.n);
      assert.equal(hex(r.chainKey()), e.chain_key_hex);
      const { counter, mac } = r.mac(Buffer.from(e.preimage_hex, 'hex'));
      assert.equal(counter, e.n);
      assert.equal(mac, e.mac_hex);
    }
  });

  test('canonical preimages match byte for byte', () => {
    for (const c of V.canonical_preimage_cases) {
      const pre = canonicalPreimage(c.fields);
      assert.equal(pre.toString('utf8'), c.canonical_utf8);
      assert.equal(hex(pre), c.canonical_hex);
      assert.equal(crypto.createHash('sha256').update(pre).digest('hex'), c.sha256_hex);
    }
  });

  test('ratchetForward reaches the same key as stepping one at a time', () => {
    const c = V.cases[0];
    const at500 = c.events.find((e) => e.n === 500)!;
    assert.equal(hex(ratchetForward(deriveIk(BDK, c.component_id), 500)), at500.chain_key_hex);
  });

  test('macFor at a cached chain key reproduces the vector MAC', () => {
    for (const c of V.cases) {
      for (const e of c.events) {
        assert.equal(
          macFor(Buffer.from(e.chain_key_hex, 'hex'), canonicalPreimage(e.preimage_fields)),
          e.mac_hex,
          `${c.component_id} n=${e.n}`,
        );
      }
    }
  });
});

// ---------------------------------------------------------------------------
// Ratchet behaviour
// ---------------------------------------------------------------------------

describe('ratchet behaviour', () => {
  test('counters advance and travel with the MAC', () => {
    const r = new Ratchet(Buffer.alloc(32, 7));
    assert.equal(r.counter, 0);
    assert.equal(r.mac(Buffer.from('a')).counter, 0);
    assert.equal(r.mac(Buffer.from('b')).counter, 1);
    assert.equal(r.counter, 2);
  });

  test('the same bytes at different counters produce different MACs', () => {
    const r = new Ratchet(Buffer.alloc(32, 7));
    const a = r.mac(Buffer.from('identical')).mac;
    const b = r.mac(Buffer.from('identical')).mac;
    assert.notEqual(a, b);
  });

  test('skip(n) and n MACs land on the same chain key', () => {
    const a = new Ratchet(Buffer.alloc(32, 3));
    const b = new Ratchet(Buffer.alloc(32, 3));
    for (let i = 0; i < 17; i++) a.mac(Buffer.from(`e${i}`));
    b.skip(17);
    assert.equal(hex(a.chainKey()), hex(b.chainKey()));
    assert.equal(a.counter, b.counter);
  });

  test('destroy() zeroes the buffer this process owns', () => {
    const key = Buffer.alloc(32, 0xab);
    const r = new Ratchet(key);
    // The Ratchet copies, so prove it on a buffer we hold ourselves.
    const own = Buffer.from(key);
    assert.ok(own.some((b) => b !== 0));
    zeroize(own);
    assert.ok(own.every((b) => b === 0));
    r.destroy();
    assert.throws(() => r.mac(Buffer.from('x')), RatchetError);
    r.destroy(); // idempotent
  });

  test('a wrong-length chain key is refused rather than padded', () => {
    assert.throws(() => new Ratchet(Buffer.alloc(31)), RatchetError);
    assert.throws(() => new Ratchet(Buffer.alloc(33)), RatchetError);
  });

  test('macEquals is length-safe and does not throw on garbage', () => {
    assert.equal(macEquals('ab', 'ab'), true);
    assert.equal(macEquals('ab', 'abc'), false);
    assert.equal(macEquals('ab', 'ac'), false);
    assert.equal(macEquals(undefined as unknown as string, 'ab'), false);
  });
});

// ---------------------------------------------------------------------------
// Isolation — the property the derivation hierarchy exists for
// ---------------------------------------------------------------------------

describe('a component cannot derive another component\'s IK from its own state', () => {
  test('nothing reachable from A\'s state is B\'s IK', () => {
    const [a, b] = V.cases;
    const ikA = deriveIk(BDK, a.component_id);
    const ikB = deriveIk(BDK, b.component_id);
    assert.notEqual(hex(ikA), hex(ikB));

    // Component A, 40 events in, holding K_40 and its own component_id.
    // It has no BDK: that is the whole architecture.
    const ra = new Ratchet(ikA, 0);
    for (let i = 0; i < 40; i++) ra.mac(Buffer.from(`event ${i}`));
    const k40 = ra.chainKey();

    const reachable = new Set<string>([hex(ikA), hex(k40)]);
    for (const info of [INFO_MAC, INFO_RATCHET, INFO_IK]) {
      reachable.add(hex(hkdfExpand(k40, info, HASH_LEN)));
      reachable.add(hex(hkdfExpand(ikA, info, HASH_LEN)));
    }
    // A tries the IK construction with every id it could name, using every
    // key it holds as the IKM — because the BDK is the one input it lacks.
    for (const ikm of [k40, ikA]) {
      for (const id of [a.component_id, b.component_id]) {
        reachable.add(hex(hkdfSha256(ikm, Buffer.from(id, 'utf8'), INFO_IK, HASH_LEN)));
        reachable.add(hex(hkdfExtract(Buffer.from(id, 'utf8'), ikm)));
      }
    }
    // and A ratcheting on for a long time regardless
    let k: Buffer = Buffer.from(k40);
    for (let i = 0; i < 500; i++) {
      k = hkdfExpand(k, INFO_RATCHET, HASH_LEN);
      reachable.add(hex(k));
    }

    assert.ok(!reachable.has(hex(ikB)), "component A reached component B's IK");

    // The positive half of the statement: with the BDK it is ONE call.
    // That asymmetry is the reason the BDK never leaves the server.
    assert.equal(hex(hkdfSha256(BDK, Buffer.from(b.component_id, 'utf8'), INFO_IK, HASH_LEN)), b.ik_hex);
  });

  test('past MAC keys are not recoverable from current state', () => {
    // "an attacker who takes the container gets future events, not history"
    const r = new Ratchet(Buffer.alloc(32, 9), 0);
    const m0 = hex(hkdfExpand(r.chainKey(), INFO_MAC, HASH_LEN));
    for (let i = 0; i < 10; i++) r.mac(Buffer.from('x'));
    let k = r.chainKey();
    for (let i = 0; i < 50; i++) {
      assert.notEqual(hex(hkdfExpand(k, INFO_MAC, HASH_LEN)), m0);
      k = hkdfExpand(k, INFO_RATCHET, HASH_LEN);
    }
  });

  test('one component_id character apart is a completely different IK', () => {
    const x = deriveIk(BDK, '0b0c9f4a-7e21-4b0d-9a3e-2c5d8f1a6b74');
    const y = deriveIk(BDK, '0b0c9f4a-7e21-4b0d-9a3e-2c5d8f1a6b75');
    assert.notEqual(hex(x), hex(y));
  });
});

// ---------------------------------------------------------------------------
// Canonical preimage — the spec gap this WO had to fill
// ---------------------------------------------------------------------------

describe('canonical preimage', () => {
  test('key order does not change the bytes', () => {
    assert.equal(
      canonicalPreimage({ b: '2', a: '1' }).toString(),
      canonicalPreimage({ a: '1', b: '2' }).toString(),
    );
  });

  test('floats are refused rather than silently formatted', () => {
    // Python repr and JS Number#toString disagree on doubles. A MAC that
    // depends on float formatting fails intermittently and unreproducibly.
    assert.throws(() => canonicalPreimage({ duration: 1.5 }), /float/);
    assert.throws(() => canonicalPreimage({ n: NaN }), /non-finite/);
    assert.throws(() => canonicalPreimage({ n: Infinity }), /non-finite/);
  });

  test('integers beyond exact representation are refused', () => {
    assert.throws(() => canonicalPreimage({ n: Number.MAX_SAFE_INTEGER + 2 }), RatchetError);
  });

  test('nested values are refused — the canonical form is flat by contract', () => {
    assert.throws(() => canonicalPreimage({ a: { b: 1 } as unknown as string }), RatchetError);
    assert.throws(() => canonicalPreimage({ a: [1] as unknown as string }), RatchetError);
  });

  test('sorting is by code point, not UTF-16 code unit', () => {
    // JS's default sort compares UTF-16 units, which puts an astral key
    // BEFORE U+E000..U+FFFF; Python sorts by code point and puts it after.
    // Same input, different JSON, different MAC — a bug that would only
    // ever appear on someone's emoji-keyed field, in production.
    const astral = '\u{1F511}'; // U+1F511, surrogate pair D83D DD11
    const bmp = '�';
    assert.ok(codePointCompare(bmp, astral) < 0);
    assert.ok([astral, bmp].sort()[0] === astral, 'default sort disagrees — which is the point');
    const out = canonicalPreimage({ [astral]: 'a', [bmp]: 'b' }).toString('utf8');
    assert.ok(out.indexOf(bmp) < out.indexOf(astral), 'code-point order must win');
  });

  test('non-ASCII survives unescaped, matching Python ensure_ascii=False', () => {
    assert.equal(canonicalPreimage({ k: 'café' }).toString('utf8'), '{"k":"café"}');
  });

  test('booleans and null are JSON literals', () => {
    assert.equal(
      canonicalPreimage({ a: true, b: false, c: null }).toString('utf8'),
      '{"a":true,"b":false,"c":null}',
    );
  });

  test('the empty preimage is legal and stable', () => {
    assert.equal(canonicalPreimage({}).toString('utf8'), '{}');
  });
});
