"""The per-leaf attestation basis. Three values, one per leaf.

Python mirror of ``lib/leaf/attestationBasis.ts``. The TypeScript file is the
one the server imports and the one the validator is written against; keep the
two in sync by hand, the same way ``surface.py`` mirrors ``surface.ts``.

Settled by the Blender×ComfyUI council (artifact ``1a978a6``, §1 and Appendix
C). ``docs/wo/2026-09-09-council-implementation.md`` WO-C1 is the work order.

ONE BASIS PER LEAF, NO PER-FIELD ``basis_ref``. The rejected alternative was a
pointer on every measured field back to the basis conditioning it, and the
reason it lost is worth keeping next to the winner: twelve fields pointing at
one basis still read as twelve measurements to anyone not following the
pointer.

WHY THREE VALUES.

    ``verified``     the quote is root-chained AND binds to THIS emission
    ``stale``        a quote exists (or is meant to) and cannot be bound; or
                     the checkpoint cannot be claimed settled
    ``passthrough``  no root-chained attestation at all

``stale`` is NOT folded into ``passthrough``. They are different operational
conditions with different fixes: ``passthrough`` says the placement has no
attestable compute and the fix is a different placement; ``stale`` says it has
one and the binding broke, and the fix is the nonce path or the checkpoint.
Collapsing them tells an operator to buy hardware they already own.

⚑ ``verified`` IS UNREACHABLE ON THE DESKTOP PROFILE BY CONSTRUCTION. Not
unlikely — unrepresentable. PCRs attest boot state; the threat is runtime root,
which can ``LD_PRELOAD`` or eBPF-synthesize the entire coverage story after the
quote was taken, and an interval bound cannot exclude a compromise inside its
own interval.

⚑ AND UNTIL WO-C6 LANDS, EVERY NEW LEAF EMITS ``stale``. Appendix C item 0:
until the witness and the verifier pass shared vectors for the canonical
preimage, domain separation, tree ordering, root calculation and proof format,
no checkpoint can be claimed settled by anybody. Three live Merkle
constructions disagree today and the witness anchors whichever root the caller
supplies, so "the root" is not a well-defined value.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Optional

__all__ = [
    "AttestationBasis",
    "CaptureProfile",
    "NonceOrigin",
    "QuoteBinding",
    "BasisResolution",
    "CHECKPOINT_VECTORS_SETTLED",
    "CHECKPOINT_BLOCKER_REASON",
    "basis_for_trust",
    "profile_for",
    "quote_binds_this_emission",
    "resolve_attestation_basis",
    "verified_is_representable",
]


class AttestationBasis(str, Enum):
    VERIFIED = "verified"
    STALE = "stale"
    PASSTHROUGH = "passthrough"


class CaptureProfile(str, Enum):
    """The three trust profiles of §1, derived from the EFFECTIVE placement.

    ``attested-client`` lands on ``DESKTOP`` deliberately: a host-signature
    check at load is a real boundary against a casual edit and no boundary at
    all against the root that can rewrite the loader, and ``attested-client``
    in this estate *is* the desktop plugin case.
    """

    SERVER_MANAGED = "server-managed"
    ISOLATED_SIDECAR = "isolated-sidecar"
    DESKTOP = "desktop"


class NonceOrigin(str, Enum):
    #: A nonce authority the capture box does not control.
    EXTERNAL_AUTHORITY = "external-authority"
    #: Generated by the box being attested. Proves nothing about freshness.
    IN_BOX = "in-box"
    NONE = "none"


#: 🔴 FALSE UNTIL WO-C6 LANDS. Flipping this is WO-C6's deliverable and no
#: test's — ``resolve_attestation_basis`` takes an explicit override so a test
#: can exercise the settled path without changing what the estate emits.
CHECKPOINT_VECTORS_SETTLED = False

CHECKPOINT_BLOCKER_REASON = (
    "the witness and the verifier do not pass shared Merkle vectors (canonical "
    "preimage, domain separation, tree ordering, root calculation, proof format). "
    "Three live constructions disagree and the witness anchors whichever root the "
    "caller supplies, so no checkpoint can be claimed settled and every new leaf "
    "states `stale`. See docs/wo/2026-09-09-council-implementation.md WO-C6 and "
    "Appendix C item 0."
)

_PLACEMENT_TO_PROFILE = {
    "server-library": CaptureProfile.SERVER_MANAGED,
    "sidecar-gate": CaptureProfile.ISOLATED_SIDECAR,
    "attested-client": CaptureProfile.DESKTOP,
    "unattested-client": CaptureProfile.DESKTOP,
}


def profile_for(effective_placement: Any) -> CaptureProfile:
    """Trust profile for an EFFECTIVE placement. Never a declared one."""
    key = getattr(effective_placement, "value", effective_placement)
    try:
        return _PLACEMENT_TO_PROFILE[key]
    except KeyError:  # pragma: no cover - a placement the model does not have
        raise ValueError(f"unknown placement {key!r}") from None


def basis_for_trust(value: Any) -> str:
    """The ONLY reader a trust decision may use.

    Absent, ``None``, malformed, a string from a future version, a number, an
    object — all ``"unknown"``. There is no branch here that returns
    ``"verified"`` for input that is not literally ``"verified"``.

    ``"unknown"`` is deliberately not a member of :class:`AttestationBasis`:
    nothing may EMIT it, because "we did not record it" is a property of an old
    row, not a claim a new leaf is entitled to make.
    """
    raw = getattr(value, "value", value)
    if isinstance(raw, str):
        for b in AttestationBasis:
            if raw == b.value:
                return b.value
    return "unknown"


def verified_is_representable(profile: CaptureProfile, enforcement: Any) -> bool:
    """Both halves of §1's sentence, and neither is redundant.

    A desktop with ``host-enforced-signature`` still fails on the profile; a
    sidecar whose namespace isolation degraded to ``none`` still fails on the
    enforcement.
    """
    enf = getattr(enforcement, "value", enforcement)
    return profile is not CaptureProfile.DESKTOP and enf != "none"


@dataclass(frozen=True)
class QuoteBinding:
    #: Did the quote chain to a vendor root? (H-5 dispatch said 'verified'.)
    root_chained: bool
    nonce_origin: NonceOrigin
    #: Does what the quote covers include THIS emission?
    covers_emission: bool


def quote_binds_this_emission(q: Optional[QuoteBinding]) -> bool:
    """All three, or the quote describes a machine at some moment instead."""
    return bool(
        q
        and q.root_chained
        and q.nonce_origin is NonceOrigin.EXTERNAL_AUTHORITY
        and q.covers_emission
    )


@dataclass(frozen=True)
class BasisResolution:
    basis: AttestationBasis
    reason: str


def resolve_attestation_basis(
    profile: CaptureProfile,
    enforcement: Any,
    quote: Optional[QuoteBinding] = None,
    vectors_settled: Optional[bool] = None,
) -> BasisResolution:
    """Order is the point, and each step is a different fact.

    1. desktop (or unenforced) → ``verified`` is unreachable;
    2. the checkpoint blocker → ``stale``, for every profile;
    3. no quote at all → ``passthrough``;
    4. a quote that does not bind THIS emission → ``stale``, never
       ``passthrough``;
    5. bound, root-chained, representable → ``verified``.
    """
    settled = CHECKPOINT_VECTORS_SETTLED if vectors_settled is None else vectors_settled
    has_quote = quote is not None

    if not verified_is_representable(profile, enforcement):
        if profile is CaptureProfile.DESKTOP:
            why = (
                "the desktop profile: the measured party has root, PCRs attest boot "
                "and the threat is runtime, so `verified` is unreachable by construction"
            )
        else:
            enf = getattr(enforcement, "value", enforcement)
            why = (
                f"enforcement {enf!r} does not keep the measured party out of the "
                "capture process"
            )
        if not settled:
            return BasisResolution(
                AttestationBasis.STALE, f"{why}; and {CHECKPOINT_BLOCKER_REASON}"
            )
        if has_quote:
            return BasisResolution(
                AttestationBasis.STALE,
                f"{why}; a quote is present and cannot be a basis here",
            )
        return BasisResolution(AttestationBasis.PASSTHROUGH, why)

    if not settled:
        return BasisResolution(AttestationBasis.STALE, CHECKPOINT_BLOCKER_REASON)

    if not has_quote:
        return BasisResolution(
            AttestationBasis.PASSTHROUGH,
            "no attestation envelope: the placement has no attestable compute, so the "
            "build↔key binding is an assertion and the receipt must read as such (§12.4)",
        )

    if not quote_binds_this_emission(quote):
        assert quote is not None
        missing = [
            m
            for m in (
                None if quote.root_chained else "it does not chain to a vendor root",
                None
                if quote.nonce_origin is NonceOrigin.EXTERNAL_AUTHORITY
                else (
                    "its freshness nonce originated "
                    + (
                        "inside the capture box"
                        if quote.nonce_origin is NonceOrigin.IN_BOX
                        else "nowhere"
                    )
                ),
                None if quote.covers_emission else "what it covers does not include this emission",
            )
            if m
        ]
        return BasisResolution(
            AttestationBasis.STALE,
            "a quote is present but cannot be bound to this emission: "
            + "; ".join(missing)
            + ". Reported as `stale` and NOT as `passthrough` — those are different "
            "operational conditions with different fixes.",
        )

    return BasisResolution(
        AttestationBasis.VERIFIED,
        "root-chained, freshness nonce from an authority outside the capture box, and "
        "the quote covers this emission",
    )
