#!/usr/bin/env bash
# WO-E3 — put a Blender that can load the addon we ship into THIS repo's tree.
#
# 🔴 Not over /usr/bin/blender. That one is 3.0.1, other work on this box may
#    depend on it, and WO-E3's own control needs it to STAY 3.0.1 so that "the
#    same zip fails to enable on 3.0.1" can be demonstrated rather than
#    asserted.
#
# ⚑ THIS BOX IS aarch64 AND blender.org PUBLISHES NO LINUX ARM64 BUILD.
#    Checked on 2026-09-09: download.blender.org/release/Blender{4.2,4.3,4.4,4.5}
#    carry linux-x64 and nothing else, and Ubuntu jammy's arm64 archive tops out
#    at the 3.0.1 already installed. So the official linux-x64 build is
#    installed and run under qemu-user with a matching amd64 sysroot. That is a
#    finding about the build matrix, recorded in docs/WO-E3.md; it is not a
#    modified Blender. The bytes under blender-*-linux-x64/ are the published
#    tarball, digest-checked below, and Blender reports its own version.
#
#    On an x86_64 host no sysroot is built and vendor/blender/bin/blender execs
#    the binary directly.
#
# Idempotent: re-running with the tree already present verifies and exits 0.
# vendor/blender/ is ~1.5 GB and is in .gitignore. What IS committed is this
# script and the two pinned digests, so the tree can be rebuilt byte-for-byte.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$PWD"

VER="${BLENDER_VERSION:-4.2.23}"     # 4.2 LTS — the series blender_manifest.toml floors at
SERIES="${VER%.*}"
TARBALL="blender-${VER}-linux-x64.tar.xz"
URL="https://download.blender.org/release/Blender${SERIES}/${TARBALL}"
# https://download.blender.org/release/Blender4.2/blender-4.2.23.sha256
SHA256="${BLENDER_SHA256:-bea0eb3146be13eae6225409a117b215184f41b7f79e799f97cb3abb8f6dc404}"

BASE_IMG="ubuntu-base-22.04.5-base-amd64.tar.gz"
BASE_URL="https://cdimage.ubuntu.com/ubuntu-base/releases/22.04/release/${BASE_IMG}"
# https://cdimage.ubuntu.com/ubuntu-base/releases/22.04/release/SHA256SUMS
BASE_SHA256="242cd8898b33ea806ef5f13b1076ed7c76f9f989d18384452f7166692438ff1a"

DEST="$ROOT/vendor/blender"
TREE="$DEST/blender-${VER}-linux-x64"
SYSROOT="$DEST/sysroot-amd64"
CACHE="$DEST/.download"
HOSTARCH="$(uname -m)"
mkdir -p "$CACHE" "$DEST/bin"

fetch(){ # url dest sha256
  [ -f "$2" ] || { echo "downloading $1"; curl -fSL --retry 3 -o "$2.part" "$1"; mv "$2.part" "$2"; }
  echo "$3  $2" | sha256sum -c - >/dev/null || { echo "!! digest mismatch on $2 — refusing"; exit 2; }
}

# ── 1. the official build ────────────────────────────────────────────────────
if [ -x "$TREE/blender" ]; then
  echo "blender tree already present: $TREE"
else
  fetch "$URL" "$CACHE/$TARBALL" "$SHA256"
  echo "extracting $TARBALL"
  tar -xJf "$CACHE/$TARBALL" -C "$DEST"
  [ -x "$TREE/blender" ] || { echo "!! $TREE/blender is not there after extract"; exit 2; }
fi

# ── 2. the amd64 sysroot, only where the host cannot run x86-64 natively ─────
RUNNER="native"
if [ "$HOSTARCH" != "x86_64" ]; then
  RUNNER="qemu"
  command -v qemu-x86_64-static >/dev/null || { echo "!! qemu-x86_64-static missing"; exit 2; }
  if [ -f "$SYSROOT/.ready" ]; then
    echo "amd64 sysroot already present: $SYSROOT"
  else
    fetch "$BASE_URL" "$CACHE/$BASE_IMG" "$BASE_SHA256"
    echo "building the amd64 sysroot (needs sudo: chroot + apt)"
    sudo rm -rf "$SYSROOT"; sudo mkdir -p "$SYSROOT"
    sudo tar -xzf "$CACHE/$BASE_IMG" -C "$SYSROOT"
    sudo cp /etc/resolv.conf "$SYSROOT/etc/resolv.conf"
    # usrmerge: /lib64 -> usr/lib64, so the loader link must be relative to THAT.
    # An absolute link resolves against the HOST root under qemu's -L prefix and
    # the ELF interpreter is then simply not found.
    sudo ln -sfn ../lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 "$SYSROOT/usr/lib64/ld-linux-x86-64.so.2"
    for m in proc dev sys; do sudo mount --bind "/$m" "$SYSROOT/$m"; done
    trap 'for m in proc dev sys; do sudo umount -l "$SYSROOT/$m" 2>/dev/null || true; done' EXIT
    # Only what `readelf -d blender` asks the system for; everything else
    # travels inside the official tarball's own lib/.
    sudo chroot "$SYSROOT" /bin/bash -c 'export DEBIAN_FRONTEND=noninteractive
      apt-get update -qq
      apt-get install -y --no-install-recommends \
        libx11-6 libxi6 libxfixes3 libxrender1 libxxf86vm1 libxkbcommon0 libxext6 \
        libstdc++6 libgcc-s1 zlib1g libsm6 libice6 libgl1 libglx0 libegl1 libgomp1 \
        libxcursor1 libxrandr2 libxinerama1 libtinfo6 ca-certificates
      apt-get clean' >/dev/null
    for m in proc dev sys; do sudo umount -l "$SYSROOT/$m" 2>/dev/null || true; done
    trap - EXIT
    sudo touch "$SYSROOT/.ready"
  fi
fi

# ── 3. one launcher, so nothing downstream has to know any of the above ──────
ln -sfn "blender-${VER}-linux-x64" "$DEST/current"
cat > "$DEST/bin/blender" <<LAUNCH
#!/usr/bin/env bash
# Generated by scripts/e3-install-blender.sh — do not edit; re-run the script.
set -euo pipefail
D="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
B="\$D/current"
LAUNCH
if [ "$RUNNER" = "qemu" ]; then
  cat >> "$DEST/bin/blender" <<'LAUNCH'
S="$D/sysroot-amd64"
# QEMU_CPU=max: Blender's own libblender_cpu_check refuses a CPU without
# SSE4.2 and qemu's default "qemu64" model does not advertise it. This changes
# what the guest is TOLD about the CPU; it does not patch Blender.
#
# QEMU_LD_PREFIX/QEMU_CPU rather than -L/-cpu because Blender's extension
# system RE-EXECS ITSELF: `--command extension install-file` runs
# scripts/addons_core/bl_pkg/cli/blender_ext.py under the bundled
# python3.11, which the kernel hands to the binfmt_misc handler, not to this
# launcher. Those two variables are what qemu-user reads from the environment,
# so the child gets the same sysroot and the same CPU as the parent. With the
# flags alone the child dies on "Could not open /lib64/ld-linux-x86-64.so.2"
# and the install reports "Package should have been installed but not found".
export QEMU_LD_PREFIX="$S"
export QEMU_CPU="${QEMU_CPU:-max}"
exec env LD_LIBRARY_PATH="$S/usr/lib/x86_64-linux-gnu:$B/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" \
  qemu-x86_64-static "$B/blender" "$@"
LAUNCH
else
  cat >> "$DEST/bin/blender" <<'LAUNCH'
exec "$B/blender" "$@"
LAUNCH
fi
chmod +x "$DEST/bin/blender"

# ── 4. the binary answers for itself. Never read a version off a path. ───────
REPORTED="$("$DEST/bin/blender" --version 2>/dev/null | sed -n 's/^Blender \([0-9.]*\).*/\1/p' | head -1 || true)"
[ -n "$REPORTED" ] || { echo "!! $DEST/bin/blender did not report a version"; exit 2; }
SYS="$(/usr/bin/blender --version 2>/dev/null | sed -n 's/^Blender \([0-9.]*\).*/\1/p' | head -1 || true)"
cat > "$DEST/INSTALLED.json" <<JSON
{
  "version": "$REPORTED",
  "requested": "$VER",
  "launcher": "vendor/blender/bin/blender",
  "runner": "$RUNNER",
  "host_arch": "$HOSTARCH",
  "tarball": "$TARBALL",
  "sha256": "$SHA256",
  "source": "$URL",
  "sysroot_base": $([ "$RUNNER" = qemu ] && echo "\"$BASE_IMG\"" || echo null),
  "installed_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "system_blender": "${SYS:-absent}"
}
JSON
echo "installed Blender $REPORTED via $RUNNER  →  vendor/blender/bin/blender"
echo "system /usr/bin/blender is still ${SYS:-absent}"
