"""Run INSIDE Blender: THE ADD-ON, ALONE. No gate, no Desktop Studio.

WO-E7 row 1. `docs/BLENDER.md`'s table says the standalone add-on has
NO byte coverage of the AI step, no graph and no model fingerprints, and
"the plugin alone stays a product". This script is that product being
used: one Blender, the shipped zip installed through the manifest path,
signed in against the scratch app, and the add-on's OWN ambient handlers
(`save_post`, `render_*`) doing the capturing. Nothing here calls
`witness_*` directly — a script that called the flow functions itself
would be measuring this file rather than the add-on.

⚑ THE POINT OF THE SCENE. The image this scene is built around came out
of a ComfyUI generation THIS BLENDER NEVER SAW — it is passed in with
`--import-image` and packed into the .blend. So the rendered pixels ARE
an AI output, and the question the work order asks is whether anything
the add-on puts on a leaf says so. This script does not answer that; it
arranges it and reports what Blender holds. `scripts/e7-gate.sh` reads
the leaf.

  blender --background --python scripts/e7-addon-alone.py -- \
      --api-key KEY --base-url URL --work DIR --import-image PNG \
      --scene NAME --camera NAME --frame N

⚑ HOME is redirected by the caller. `scruple_host_sdk.auth` writes its
key cache to `~/.scruple/blender-auth.json` with no environment override,
so the only way to keep a run out of the real one is to move HOME.

⚑ SCRUPLE_COMFY_HOST_DIR MUST NOT BE SET. If it is, the add-on writes a
host declaration for a gate — and this run is the one with no gate. The
script reports what it found rather than unsetting it, so the gate can
fail on a run that was quietly Level 2.
"""

import json
import os
import sys
import time

import bpy

MARK_OPEN = "<<<E7_ADDON"
MARK_CLOSE = "E7_ADDON>>>"


def argv():
    args = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    out = {}
    i = 0
    while i < len(args):
        out[args[i].lstrip("-")] = args[i + 1]
        i += 2
    return out


def addon_module():
    for a in bpy.context.preferences.addons:
        if a.module.endswith("scruple_blender"):
            return a.module
    return None


def build_scene(a, report):
    """One plane, one emission material, one image, one camera.

    The image is PACKED, so the AI-generated bytes are inside the .blend
    the add-on witnesses as a `document_save` and not merely referenced
    by a path.
    """
    scene = bpy.context.scene
    scene.name = a.get("scene", "e7-scene")

    for ob in list(bpy.data.objects):
        bpy.data.objects.remove(ob, do_unlink=True)

    img = bpy.data.images.load(a["import-image"])
    img.name = "imported-from-somewhere-else"
    img.pack()
    report["imported_image"] = {
        "datablock": img.name,
        "source_path": a["import-image"],
        "packed": bool(img.packed_file),
        "size": list(img.size),
    }

    bpy.ops.mesh.primitive_plane_add(size=2.0, location=(0, 0, 0))
    plane = bpy.context.active_object
    plane.name = "screen"
    mat = bpy.data.materials.new("emit-the-import")
    mat.use_nodes = True
    nt = mat.node_tree
    for n in list(nt.nodes):
        nt.nodes.remove(n)
    tex = nt.nodes.new("ShaderNodeTexImage")
    tex.image = img
    emit = nt.nodes.new("ShaderNodeEmission")
    out = nt.nodes.new("ShaderNodeOutputMaterial")
    nt.links.new(tex.outputs["Color"], emit.inputs["Color"])
    nt.links.new(emit.outputs["Emission"], out.inputs["Surface"])
    plane.data.materials.append(mat)

    cam_data = bpy.data.cameras.new(a.get("camera", "CAM_e7"))
    cam_data.type = "ORTHO"
    cam_data.ortho_scale = 2.0
    cam = bpy.data.objects.new(a.get("camera", "CAM_e7"), cam_data)
    scene.collection.objects.link(cam)
    cam.location = (0, 0, 4)
    scene.camera = cam

    scene.frame_set(int(a.get("frame", 1)))
    # CYCLES because this box has no GPU and EEVEE Next cannot render in
    # background mode. One sample: nothing here is gated on a pixel.
    scene.render.engine = "CYCLES"
    scene.cycles.samples = int(a.get("samples", 1))
    scene.cycles.use_denoising = False
    scene.render.resolution_x = int(a.get("width", 64))
    scene.render.resolution_y = int(a.get("height", 64))
    scene.render.image_settings.file_format = "PNG"
    scene.render.filepath = os.path.join(a["work"], "e7-render")
    return scene


def main():
    a = argv()
    work = a["work"]
    os.makedirs(work, exist_ok=True)

    report = {
        "blender_version": ".".join(str(x) for x in bpy.app.version),
        "module": addon_module(),
        "loaded_via_manifest": (addon_module() or "").startswith("bl_ext."),
        # ⚑ Reported, never unset here. A run in which this is set is a run
        # with a gate in it, and the gate must be able to say so.
        "host_dir_env": os.environ.get("SCRUPLE_COMFY_HOST_DIR"),
        "home": os.environ.get("HOME"),
    }

    mod = addon_module()
    if mod is None:
        report["error"] = "the Scruple add-on is not enabled in this profile"
        emit(report)
        return

    # ⚑ THE LIVE MODULES ARE TOP-LEVEL, not attributes of the extension
    # package. The add-on's `__init__.py` puts its own directory on sys.path
    # and does `from adapter import handlers`, so the module that installed the
    # handlers and owns the worker thread and the state bag is `adapter.handlers`
    # — NOT `bl_ext.user_default.scruple_blender.adapter.handlers`. Importing
    # the dotted name here would load a SECOND copy with a worker that was
    # never started and a state bag nothing writes to, and this script would
    # report an empty run for a Blender that had witnessed perfectly well. It
    # did, once, and that is why this comment is longer than the import.
    from adapter import preferences as prefs
    from adapter import sdk as sdkmod
    from adapter import handlers
    from adapter import state
    from scruple_host_sdk import auth as sdk_auth

    # ⚑ FINDING E7-2, recorded as a measurement rather than worked around.
    # `ScrupleAddonPreferences.bl_idname` is the string "scruple_blender",
    # which was the module name on the legacy scripts/addons path. Under an
    # extension the module is `bl_ext.user_default.scruple_blender`, Blender
    # never binds the class, and `addons[module].preferences` is None — so the
    # add-on's own Settings UI does not draw and there is nowhere to paste a
    # key. What still works is the SDK's on-disk auth cache, which is what the
    # `scruple.sign_in` operator writes; so that is how this run signs in,
    # exactly as a signed-in user's Blender would read it.
    ap = bpy.context.preferences.addons[mod]
    report["addon_preferences_bound"] = getattr(ap, "preferences", None) is not None
    report["addon_preferences_bl_idname"] = prefs.ScrupleAddonPreferences.bl_idname
    report["base_url_before_sign_in"] = prefs.get_base_url()

    sdk_auth.save_cached("blender", a["api-key"], a["base-url"])
    sdkmod.reset_client()
    report["signed_in"] = prefs.is_authed()
    report["base_url"] = prefs.get_base_url()
    report["auth_cache"] = os.path.join(os.path.expanduser("~"), ".scruple", "blender-auth.json")

    scene = build_scene(a, report)
    report["scene"] = scene.name
    report["frame"] = int(scene.frame_current)
    report["camera"] = scene.camera.name
    report["engine"] = scene.render.engine
    report["resolution"] = [scene.render.resolution_x, scene.render.resolution_y]
    report["samples"] = int(scene.cycles.samples)
    report["file_format"] = scene.render.image_settings.file_format
    # Every image datablock in the file, so the gate can say what was in the
    # document at the moment it was witnessed.
    report["image_datablocks"] = sorted(i.name for i in bpy.data.images)

    blend_path = os.path.join(work, "e7-addon-alone.blend")
    t0 = time.time()
    bpy.ops.wm.save_as_mainfile(filepath=blend_path)
    report["blend_path"] = blend_path
    report["blend_exists"] = os.path.exists(blend_path)
    # scene_inventory() is read AFTER the save, because that is when the
    # handler read it. `object_count` is the scene's, `material_count` is
    # bpy.data's — the add-on's own definition, not this script's.
    report["object_count"] = len(list(scene.objects))
    report["material_count"] = len(list(bpy.data.materials))

    bpy.ops.render.render(write_still=True)
    report["render_seconds"] = round(time.time() - t0, 2)
    render_path = scene.render.filepath + ".png"
    report["render_path"] = render_path
    report["render_exists"] = os.path.exists(render_path)

    # The add-on's captures run on ITS worker thread. A headless run has to
    # wait for what a user's Blender would do while they carried on working;
    # nothing here retries and nothing here submits.
    #
    # ⚑ IT WAITS FOR QUIESCENCE AND DOES NOT JUST CALL stop(). `WitnessWorker.
    # stop()` sets a flag and puts a no-op on the queue, and `_run()` re-checks
    # the flag BEFORE running whatever it pulled — so any capture still queued
    # when stop() is called is dropped on the floor. A script that stopped the
    # worker the moment the render returned would silently under-count the
    # add-on's captures and would be measuring its own impatience. Finding
    # E7-3: the same call is what `unregister()` makes when Blender quits.
    quiet = float(a.get("quiet-seconds", 8))
    deadline = time.time() + float(a.get("settle-seconds", 240))
    seen, last_change = len(state.get().assurances), time.time()
    while time.time() < deadline and time.time() - last_change < quiet:
        time.sleep(0.5)
        now = len(state.get().assurances)
        if now != seen:
            seen, last_change = now, time.time()
    report["captures_before_stop"] = seen
    handlers.WORKER.stop(timeout=30.0)
    report["captures_after_stop"] = len(state.get().assurances)
    report["worker_alive_after_stop"] = bool(
        handlers.WORKER._thread and handlers.WORKER._thread.is_alive()
    )

    client = sdkmod.peek_client()
    report["queue_depth"] = client.queue_depth if client is not None else None
    report["baseline_ref"] = client.state.baseline_ref if client is not None else None
    report["receipts"] = [dict(r) for r in (client.state.recent_receipts if client else [])]
    st = state.get()
    report["last_error"] = st.last_error
    # The assurance records carry the workflow hash the ADD-ON computed with
    # its own canonicalizer, before anything was sent. The gate compares that
    # against what the server put on the leaf.
    # The add-on's own assurance records, as the add-on serialises them. They
    # carry `canonicalization.client_workflow_hash` — the hash the add-on
    # computed with its own canonicalizer BEFORE anything was sent — which is
    # what lets the gate prove the graph on the leaf is the graph the add-on
    # composed.
    report["assurances"] = [r.to_dict() for r in st.assurances]
    emit(report)


def emit(report):
    sys.stdout.write("\n" + MARK_OPEN + "\n" + json.dumps(report, indent=1, default=str) + "\n" + MARK_CLOSE + "\n")
    sys.stdout.flush()


main()
