// scruple-verify watermark subcommand.
//
// Reads a Scruple watermark from an image and reports the decoded
// payload + dispatched resolution path per WATERMARK_DESIGN_v1.md §3.2.
//
// Tier 1-3 (self-contained): "AI-generated by Scruple pipeline at time T".
//                            Verifier UX stops there; artist controls
//                            downstream disclosure of the manifest.
// Tier 4-5 (chain-locked):   Decodes SCR_ID → suggests RVN lookup. When
//                            tier 5, additionally reports the pinned_hint
//                            for IPFS + Arweave.
//
// Delegates the actual DCT decoding to the Python reference at
// services/watermark. Reason: implementing the DCT + Reed-Solomon
// decoder in Node.js would double the maintenance burden with zero
// user-facing benefit for the MVP. Follow-up: WASM or native Node
// bindings if third-party integrators need a pure-JS decoder.

import { readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');

export async function verifyWatermark({ inputSource, json, quiet }) {
  const steps = [];
  const record = (name, ok, detail) => {
    steps.push({ name, ok, detail });
    if (!quiet && !json) {
      const mark = ok ? 'ok  ' : 'FAIL';
      console.log(`  ${mark} — ${name}${detail ? '  ' + detail : ''}`);
    }
  };

  if (!inputSource) {
    console.error('scruple-verify watermark --input <path-to-image>');
    process.exit(2);
  }

  let bytes;
  try {
    bytes = readFileSync(inputSource);
  } catch (e) {
    record('input readable', false, `  ${e.message}`);
    if (json) console.log(JSON.stringify({ verdict: 'INVALID', steps }, null, 2));
    process.exit(1);
  }
  record('input readable', true, `  ${bytes.length} bytes`);

  // Dispatch to the Python decoder via the same CLI the server uses
  const res = spawnSync(
    'python3',
    ['-m', 'services.watermark.cli'],
    {
      input: JSON.stringify({ action: 'decode', input_path: inputSource }),
      encoding: 'utf-8',
      cwd: REPO_ROOT,
    },
  );
  if (res.status !== 0) {
    record('decoder invoked', false, `  python failed: ${res.stderr || res.stdout}`);
    if (json) console.log(JSON.stringify({ verdict: 'INVALID', steps }, null, 2));
    process.exit(1);
  }
  const decoded = JSON.parse(res.stdout.trim().split('\n').at(-1) || '{}');
  if (!decoded.ok) {
    record('decoder succeeded', false, `  ${decoded.error ?? 'unknown'}`);
    if (json) console.log(JSON.stringify({ verdict: 'INVALID', steps }, null, 2));
    process.exit(1);
  }

  if (!decoded.decoded) {
    record('watermark present', false, '  no Scruple watermark found');
    if (!quiet && !json) console.log('\nVerdict: NO_WATERMARK');
    if (json) console.log(JSON.stringify({ verdict: 'NO_WATERMARK', steps }, null, 2));
    process.exit(0);
  }

  record('watermark present', true);
  const d = decoded.decoded;
  const tier = d.tier;
  const version = d.version;
  const tierName = d.tier_name || `tier-${tier}`;

  record(`payload version v${version}, tier ${tier} (${tierName})`, true);

  const verdict = {
    verdict: 'VALID',
    watermark: {
      version,
      tier,
      tier_name: tierName,
    },
    dispatch: null,
  };

  if (tier >= 1 && tier <= 3) {
    // Self-contained tier — no lookup
    const signedAt = d.signed_at_unix_seconds;
    const iso = signedAt ? new Date(signedAt * 1000).toISOString() : null;
    if (iso) record(`signed_at = ${iso}`, true);
    verdict.watermark.signed_at_unix_seconds = signedAt;
    verdict.watermark.signed_at_iso = iso;
    verdict.dispatch = {
      type: 'self-contained',
      resolution: (
        'This is a Scruple-marked AI-generated artifact. The mark says ' +
        '"AI-generated at time T" and does not encode artist identity. ' +
        'To identify the artist or retrieve the C2PA manifest, obtain the ' +
        'receipt directly from the artist or from any location where they ' +
        'have chosen to publish it (e.g. IPFS).'
      ),
    };
  } else if (tier === 4 || tier === 5) {
    const scrId = d.scr_id;
    record(`scr_id = ${scrId}`, true);
    verdict.watermark.scr_id = scrId;
    if (tier === 5) {
      verdict.watermark.pinned_hint = d.pinned_hint;
    }
    verdict.dispatch = {
      type: 'chain-lock',
      resolution: (
        `SCR_ID ${scrId} is a public Ravencoin asset. Query any RVN explorer ` +
        `for the asset by name to fetch the anchored content hash. ` +
        (tier === 5 ? `pinned_hint indicates IPFS + Arweave permanence anchors are available. ` : '') +
        `The provenance package itself remains with the artist or in the ` +
        `public locations they chose (IPFS/Arweave when pinned).`
      ),
    };
  } else {
    verdict.dispatch = {
      type: 'unknown',
      resolution: `Tier ${tier} not defined in this spec version.`,
    };
  }

  if (json) {
    console.log(JSON.stringify(verdict, null, 2));
  } else if (!quiet) {
    console.log(`\nVerdict: ${verdict.verdict}`);
    console.log(`\nDispatch: ${verdict.dispatch.type}`);
    console.log(verdict.dispatch.resolution);
  } else {
    console.log('PASS');
  }
  process.exit(0);
}
