// GENERATED FILE — DO NOT EDIT.
// Source: lib/leaf/registry.yaml · Emitter: lib/leaf/generate.mjs
// Regenerate with `npm run gen:leaf-registry`.
// test/v2/leaf-registry.test.ts fails if this file and the YAML disagree.

export type LeafSurface = 'submit' | 'record' | 'response' | 'storage';
export type LeafRequirementLevel = 'required' | 'conditionally_required' | 'recommended' | 'opt_in';
export type LeafStability = 'stable' | 'development';

export interface LeafFieldDeprecation {
  reason: string;
  renamed_to?: string;
  note?: string;
}

export interface LeafField {
  id: string;
  group: string;
  type: string;
  stability: LeafStability;
  requirement_level: LeafRequirementLevel;
  condition?: string;
  /** Leaf scheme version in which the field first appeared. */
  introduced_in: string;
  surfaces: LeafSurface[];
  /** Surface-specific spelling, where it differs from `id`. */
  aliases: Partial<Record<LeafSurface, string>>;
  deprecated?: LeafFieldDeprecation;
  brief: string;
  preimage?: string;
}

/** Field ids, as a union — so a typo in a lookup is a compile error. */
export type LeafFieldId =
  | 'project_id'
  | 'project_name'
  | 'run_sequence'
  | 'output_hash'
  | 'input_hash'
  | 'workflow_hash'
  | 'model_fingerprints_hash'
  | 'machine_manifest_hash'
  | 'visual_hash'
  | 'client_timestamp'
  | 'server_timestamp'
  | 'prev_record_hash'
  | 'witness_id'
  | 'leaf_hash'
  | 'leaf_scheme'
  | 'signature'
  | 'leaf_signature'
  | 'leaf_signer_key_id'
  | 'leaf_signature_alg'
  | 'signer_surrogate'
  | 'independently_verifiable'
  | 'leaf_signer_surrogate'
  | 'content_hash';

export const LEAF_FIELDS: readonly LeafField[] = [
  {
    id: "project_id",
    group: "registry.witness-leaf",
    type: "string",
    stability: "stable",
    requirement_level: "required",
    introduced_in: "v1",
    surfaces: ["submit","storage"],
    aliases: {},
    brief: "Chain identity. Every leaf's prev_record_hash is looked up within this id, so two callers sharing one project_id share one chain. The production witness REFUSES ids prefixed `tenant:` or `baseline:` — those are generated by the /v2 canon surface and their arrival means a developer is pointed at production.",
  },
  {
    id: "project_name",
    group: "registry.witness-leaf",
    type: "string",
    stability: "stable",
    requirement_level: "opt_in",
    introduced_in: "v1",
    surfaces: ["submit","storage"],
    aliases: {},
    brief: "Display name. Audit-log convenience; not in the preimage.",
  },
  {
    id: "run_sequence",
    group: "registry.witness-leaf",
    type: "int",
    stability: "stable",
    requirement_level: "required",
    introduced_in: "v1",
    surfaces: ["submit","record","storage"],
    aliases: {},
    brief: "Position in the project's chain, 1-based. In the preimage, so a leaf cannot be reordered after the fact. Hardcoding it to a constant does not fail on the first call, only on the second — which is how it survived in two separate code paths.",
  },
  {
    id: "output_hash",
    group: "registry.witness-leaf",
    type: "string",
    stability: "stable",
    requirement_level: "required",
    introduced_in: "v1",
    surfaces: ["submit","record","storage"],
    aliases: {"submit":"content_hash","storage":"content_hash"},
    brief: "The artifact itself. NOTE THE ALIASES. The wire says content_hash and the `witnesses` column says content_hash; only the PREIMAGE says output_hash — so the one name that appears nowhere a developer normally looks is the one the evidence is built from. Found by writing this registry, not by debugging: the first draft assumed the column matched the preimage, and the drift guard said otherwise on its first run. Recorded rather than reconciled — see the deprecated group.",
    preimage: "sha256 of the raw output bytes.",
  },
  {
    id: "input_hash",
    group: "registry.witness-leaf",
    type: "string",
    stability: "stable",
    requirement_level: "recommended",
    introduced_in: "v2",
    surfaces: ["submit","record","storage"],
    aliases: {},
    brief: "Binds every input artifact that fed the run.",
    preimage: "sha256(JSON.stringify({provider, prompt, spec, inputs})) with the keys in that literal order and each input reduced to {kind, hash}. NOT canonical (recursively key-sorted) JSON — this is what shipped and existing leaves commit to it. lib/leaf/hashes.ts#hashRunInputs is the only implementation. The /v2 surface passes null for provider/prompt/spec because it is zero-content and never receives them.",
  },
  {
    id: "workflow_hash",
    group: "registry.witness-leaf",
    type: "string",
    stability: "stable",
    requirement_level: "recommended",
    introduced_in: "v2",
    surfaces: ["submit","record","storage"],
    aliases: {},
    brief: "Binds the graph, or the training recipe, that produced the output.",
    preimage: "sha256(canonicalize(doc)) — recursive key sort, arrays keep order, no whitespace (lib/scruple/canonicalWorkflow.ts). `doc` is the ComfyUI workflow_api_json for kind=graph_execute, and the training recipe for kind=model_write: on a training run the recipe is what the graph is on a generation run. `kind` tells a verifier which document to re-canonicalize.",
  },
  {
    id: "model_fingerprints_hash",
    group: "registry.witness-leaf",
    type: "string",
    stability: "stable",
    requirement_level: "recommended",
    introduced_in: "v2",
    surfaces: ["submit","record","storage"],
    aliases: {},
    brief: "Binds the actual weights loaded, not the filenames asked for.",
    preimage: "sha256(JSON.stringify(manifest)) with TOP-LEVEL keys sorted ascending and nested per-file objects left in their original key order. Deliberately not recursive; see lib/leaf/hashes.ts. Absent or empty manifest hashes to NULL, never to the hash of {} — \"we looked and found none\" is a claim, and an unpopulated field must not make it.",
  },
  {
    id: "machine_manifest_hash",
    group: "registry.witness-leaf",
    type: "string",
    stability: "stable",
    requirement_level: "conditionally_required",
    condition: "Present whenever the toolchain is pinned. Its presence is what selects leaf_scheme v2.2 over v2, so it is not a free-form optional: supplying it changes the preimage shape.",
    introduced_in: "v2.2",
    surfaces: ["submit","record","storage"],
    aliases: {},
    brief: "Binds the custom-node pack manifest the workflow ran on.",
  },
  {
    id: "visual_hash",
    group: "registry.witness-leaf",
    type: "string",
    stability: "stable",
    requirement_level: "opt_in",
    introduced_in: "v1",
    surfaces: ["submit","storage"],
    aliases: {},
    brief: "Perceptual hash. Stored, never in the preimage — a fuzzy hash in a tamper-evidence record would make the record fuzzy.",
  },
  {
    id: "client_timestamp",
    group: "registry.witness-leaf",
    type: "string",
    stability: "stable",
    requirement_level: "recommended",
    introduced_in: "v1",
    surfaces: ["submit","storage"],
    aliases: {},
    brief: "When the caller says it happened. Not in the preimage: the caller is the party the leaf is evidence about.",
  },
  {
    id: "server_timestamp",
    group: "registry.witness-leaf",
    type: "string",
    stability: "stable",
    requirement_level: "required",
    introduced_in: "v1",
    surfaces: ["record","response","storage"],
    aliases: {},
    brief: "When the witness saw it. This is the one in the preimage.",
  },
  {
    id: "prev_record_hash",
    group: "registry.witness-leaf",
    type: "string",
    stability: "stable",
    requirement_level: "required",
    introduced_in: "v2",
    surfaces: ["record","response","storage"],
    aliases: {},
    brief: "The previous leaf_hash in this project's chain, '' at genesis. What makes the sequence append-only rather than merely ordered.",
  },
  {
    id: "witness_id",
    group: "registry.witness-leaf",
    type: "string",
    stability: "stable",
    requirement_level: "required",
    introduced_in: "v1",
    surfaces: ["response","storage"],
    aliases: {},
    brief: "Opaque id, `wit_` + 8 random bytes.",
  },
  {
    id: "leaf_hash",
    group: "registry.witness-leaf",
    type: "string",
    stability: "stable",
    requirement_level: "required",
    introduced_in: "v2",
    surfaces: ["response","storage"],
    aliases: {},
    brief: "sha256 of the canonical record. The Merkled leaf.",
  },
  {
    id: "leaf_scheme",
    group: "registry.witness-leaf",
    type: "string",
    stability: "stable",
    requirement_level: "required",
    introduced_in: "v2",
    surfaces: ["response","storage"],
    aliases: {},
    brief: "Which record_order above reproduces leaf_hash. Without it an auditor cannot replay a historical leaf at all.",
  },
  {
    id: "signature",
    group: "registry.witness-leaf",
    type: "string",
    stability: "stable",
    requirement_level: "required",
    introduced_in: "v1",
    surfaces: ["response","storage"],
    aliases: {},
    brief: "HMAC over leaf_hash. H-2 demoted this to a TRANSPORT SEAL between the application tier and the witness; it is not an evidence claim, because both parties hold the key. Kept under its original name rather than renamed, because renaming it would make old rows and new rows look like different things when they are the same thing.",
  },
  {
    id: "leaf_signature",
    group: "registry.witness-leaf",
    type: "string",
    stability: "development",
    requirement_level: "recommended",
    introduced_in: "v2.4",
    surfaces: ["response","storage"],
    aliases: {},
    brief: "H-1. Base64 DER ECDSA P-256 over the raw bytes of leaf_hash — the seal a third party can check without Scruple. NULL when signing is disabled or the KMS is unreachable, because losing the event would be worse than recording one whose independent verifiability is pending. `stability: development` is not hedging: nothing on the scruple-web side reads it yet (migration 041 is unwritten), so it is defined-and-not-wired and the registry says so rather than leaving it to be discovered.",
  },
  {
    id: "leaf_signer_key_id",
    group: "registry.witness-leaf",
    type: "string",
    stability: "development",
    requirement_level: "recommended",
    introduced_in: "v2.4",
    surfaces: ["response","storage"],
    aliases: {},
    brief: "Which key signed. Also unread on the scruple-web side.",
  },
  {
    id: "leaf_signature_alg",
    group: "registry.witness-leaf",
    type: "string",
    stability: "development",
    requirement_level: "recommended",
    introduced_in: "v2.4",
    surfaces: ["response","storage"],
    aliases: {},
    brief: "Signature algorithm. Also unread on the scruple-web side.",
  },
  {
    id: "signer_surrogate",
    group: "registry.witness-leaf",
    type: "boolean",
    stability: "development",
    requirement_level: "recommended",
    introduced_in: "v2.4",
    surfaces: ["response","storage"],
    aliases: {"storage":"leaf_signer_surrogate"},
    brief: "True when a software surrogate key signed rather than the vault key. NOTE THE ALIAS — this is the drift WO-1 was sent to settle. The wire says signer_surrogate; the column says leaf_signer_surrogate. Reading the column name off the wire yields undefined forever, and WitnessIterationResult's index signature means TypeScript will not object.",
  },
  {
    id: "independently_verifiable",
    group: "registry.witness-leaf",
    type: "boolean",
    stability: "development",
    requirement_level: "recommended",
    introduced_in: "v2.4",
    surfaces: ["response"],
    aliases: {},
    brief: "Whether an asymmetric signature exists at all. Response-only by design: it is derived from leaf_signature, and a stored copy could disagree with the field it summarises.",
  },
  {
    id: "leaf_signer_surrogate",
    group: "registry.witness-leaf.deprecated",
    type: "boolean",
    stability: "development",
    requirement_level: "opt_in",
    introduced_in: "v2.4",
    surfaces: [],
    aliases: {},
    deprecated: {"reason":"renamed","renamed_to":"signer_surrogate","note":"Storage-side spelling only. NOT reconciled, deliberately: changing the wire field is breaking, and while a grep found no consumer inside this repo, the deployed witness (2026-07-16 build) predates H-1 entirely and any external verifier written against the current wire would break for a cosmetic gain. Recorded, guarded by test/v2/leaf-registry.test.ts, and left alone."},
    brief: "See signer_surrogate.",
  },
  {
    id: "content_hash",
    group: "registry.witness-leaf.deprecated",
    type: "string",
    stability: "stable",
    requirement_level: "opt_in",
    introduced_in: "v1",
    surfaces: [],
    aliases: {},
    deprecated: {"reason":"renamed","renamed_to":"output_hash","note":"The spelling used on BOTH the wire and the `witnesses` column; `output_hash` exists only inside the canonical record. Same reasoning as leaf_signer_surrogate — a live wire field is not renamed for tidiness — with more force here, because renaming the column would also rewrite the table every existing leaf lives in."},
    brief: "See output_hash.",
  },
] as const;

/** Preimage field order per leaf scheme. Order IS the protocol. */
export const LEAF_SCHEMES: Readonly<Record<string, readonly string[]>> = {
  "v1": [],
  "v2": ["run_sequence","output_hash","input_hash","workflow_hash","model_fingerprints_hash","server_timestamp","prev_record_hash"],
  "v2.2": ["run_sequence","output_hash","input_hash","workflow_hash","model_fingerprints_hash","machine_manifest_hash","server_timestamp","prev_record_hash"],
};

/** Source files the drift guard reads for each surface. */
export const LEAF_SURFACE_EMITTERS: Readonly<Record<string, readonly string[]>> = {
  "submit": ["services/witness-server/server.js","app/api/v2/witness/route.ts"],
  "record": ["services/witness-server/server.js"],
  "response": ["services/witness-server/server.js"],
  "storage": ["services/witness-server/server.js"],
};
